# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 500000 # 500000 for 6h_vs_8z

runner: "parallel"
batch_size_run: 8 # batch_size_run=4, buffer_size = 2500, batch_size=64  for 3s5z_vs_3s6z
buffer_size: 5000
batch_size: 128

t_max: 10050000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "hpn_mac"

agent: "hpns_rnn"

hpn_hyper_dim: 64
hpn_hyper_activation: 'relu'

hpn_head_num: 1 # 2 for 3s_vs_5z and 6h_vs_8z
agent_output_type: q

learner: "nq_learner"
mixer: "qmix"
mixing_embed_dim: 32
hypernet_embed: 64
lr: 0.0006 # Learning rate for agents
td_lambda: 0.6 # 0.3 for 6h_vs_8z
optimizer: 'adam'
q_lambda: False


name: "ir_qmix"

obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: False # Include the agent's last action (one_hot) in the observation

q_transformer_head_num: 4

#random_rotation_data_augmentation: False # use rotation data to augmentation
#seq_update: True
#rotate_times: 3

# critic use graph state
use_graph_state: True